/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/t/Desktop/repo/src/cpp/ros/camera_node/msg/matrix3x3.msg
 *
 */


#ifndef CAMERA_NODE_MESSAGE_MATRIX3X3_H
#define CAMERA_NODE_MESSAGE_MATRIX3X3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_node
{
template <class ContainerAllocator>
struct matrix3x3_
{
  typedef matrix3x3_<ContainerAllocator> Type;

  matrix3x3_()
    : values()  {
      values.assign(0.0);
  }
  matrix3x3_(const ContainerAllocator& _alloc)
    : values()  {
      values.assign(0.0);
  }



   typedef boost::array<double, 9>  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::camera_node::matrix3x3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_node::matrix3x3_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct matrix3x3_

typedef ::camera_node::matrix3x3_<std::allocator<void> > matrix3x3;

typedef boost::shared_ptr< ::camera_node::matrix3x3 > matrix3x3Ptr;
typedef boost::shared_ptr< ::camera_node::matrix3x3 const> matrix3x3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_node::matrix3x3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_node::matrix3x3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'camera_node': ['/home/t/Desktop/repo/src/cpp/ros/camera_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_node::matrix3x3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_node::matrix3x3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_node::matrix3x3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_node::matrix3x3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_node::matrix3x3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_node::matrix3x3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_node::matrix3x3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c2377c56eaa1968dfc8719f26aebb7b";
  }

  static const char* value(const ::camera_node::matrix3x3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c2377c56eaa1968ULL;
  static const uint64_t static_value2 = 0xdfc8719f26aebb7bULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_node::matrix3x3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_node/matrix3x3";
  }

  static const char* value(const ::camera_node::matrix3x3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_node::matrix3x3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[9] values\n\
\n\
";
  }

  static const char* value(const ::camera_node::matrix3x3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_node::matrix3x3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct matrix3x3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_node::matrix3x3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_node::matrix3x3_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_NODE_MESSAGE_MATRIX3X3_H
