(cl:defpackage camera_node-srv
  (:use )
  (:export
   "CORRECTIONMATRICES"
   "<CORRECTIONMATRICES-REQUEST>"
   "CORRECTIONMATRICES-REQUEST"
   "<CORRECTIONMATRICES-RESPONSE>"
   "CORRECTIONMATRICES-RESPONSE"
   "AUTOWHITEBALANCE"
   "<AUTOWHITEBALANCE-REQUEST>"
   "AUTOWHITEBALANCE-REQUEST"
   "<AUTOWHITEBALANCE-RESPONSE>"
   "AUTOWHITEBALANCE-RESPONSE"
   "FISHEYECORRECTION"
   "<FISHEYECORRECTION-REQUEST>"
   "FISHEYECORRECTION-REQUEST"
   "<FISHEYECORRECTION-RESPONSE>"
   "FISHEYECORRECTION-RESPONSE"
  ))

