"""autogenerated by genpy from qr_code_reader_node/Collection.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import qr_code_reader_node.msg

class Collection(genpy.Message):
  _md5sum = "ed88e26dc0877b4b4774687d132d3b67"
  _type = "qr_code_reader_node/Collection"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """qrCode[] collection

================================================================================
MSG: qr_code_reader_node/qrCode
string value
point64[3] corners

================================================================================
MSG: qr_code_reader_node/point64
float64 x
float64 y

"""
  __slots__ = ['collection']
  _slot_types = ['qr_code_reader_node/qrCode[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       collection

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Collection, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.collection is None:
        self.collection = []
    else:
      self.collection = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.collection)
      buff.write(_struct_I.pack(length))
      for val1 in self.collection:
        _x = val1.value
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        for val2 in val1.corners:
          _x = val2
          buff.write(_struct_2d.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.collection is None:
        self.collection = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.collection = []
      for i in range(0, length):
        val1 = qr_code_reader_node.msg.qrCode()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.value = str[start:end].decode('utf-8')
        else:
          val1.value = str[start:end]
        val1.corners = []
        for i in range(0, 3):
          val2 = qr_code_reader_node.msg.point64()
          _x = val2
          start = end
          end += 16
          (_x.x, _x.y,) = _struct_2d.unpack(str[start:end])
          val1.corners.append(val2)
        self.collection.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.collection)
      buff.write(_struct_I.pack(length))
      for val1 in self.collection:
        _x = val1.value
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        for val2 in val1.corners:
          _x = val2
          buff.write(_struct_2d.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.collection is None:
        self.collection = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.collection = []
      for i in range(0, length):
        val1 = qr_code_reader_node.msg.qrCode()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.value = str[start:end].decode('utf-8')
        else:
          val1.value = str[start:end]
        val1.corners = []
        for i in range(0, 3):
          val2 = qr_code_reader_node.msg.point64()
          _x = val2
          start = end
          end += 16
          (_x.x, _x.y,) = _struct_2d.unpack(str[start:end])
          val1.corners.append(val2)
        self.collection.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d = struct.Struct("<2d")
