/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/t/Desktop/repo/src/cpp/ros/camera_calibration_node/srv/CalibrateLens.srv
 *
 */


#ifndef CAMERA_CALIBRATION_NODE_MESSAGE_CALIBRATELENSREQUEST_H
#define CAMERA_CALIBRATION_NODE_MESSAGE_CALIBRATELENSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_calibration_node
{
template <class ContainerAllocator>
struct CalibrateLensRequest_
{
  typedef CalibrateLensRequest_<ContainerAllocator> Type;

  CalibrateLensRequest_()
    : frameCount(0)
    , boardWidth(0)
    , boardHeight(0)  {
    }
  CalibrateLensRequest_(const ContainerAllocator& _alloc)
    : frameCount(0)
    , boardWidth(0)
    , boardHeight(0)  {
    }



   typedef int32_t _frameCount_type;
  _frameCount_type frameCount;

   typedef int32_t _boardWidth_type;
  _boardWidth_type boardWidth;

   typedef int32_t _boardHeight_type;
  _boardHeight_type boardHeight;




  typedef boost::shared_ptr< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct CalibrateLensRequest_

typedef ::camera_calibration_node::CalibrateLensRequest_<std::allocator<void> > CalibrateLensRequest;

typedef boost::shared_ptr< ::camera_calibration_node::CalibrateLensRequest > CalibrateLensRequestPtr;
typedef boost::shared_ptr< ::camera_calibration_node::CalibrateLensRequest const> CalibrateLensRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_calibration_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df5f0df29ff7353b56dd0a78a901860e";
  }

  static const char* value(const ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf5f0df29ff7353bULL;
  static const uint64_t static_value2 = 0x56dd0a78a901860eULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_calibration_node/CalibrateLensRequest";
  }

  static const char* value(const ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 frameCount\n\
int32 boardWidth\n\
int32 boardHeight\n\
\n\
";
  }

  static const char* value(const ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frameCount);
      stream.next(m.boardWidth);
      stream.next(m.boardHeight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CalibrateLensRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_calibration_node::CalibrateLensRequest_<ContainerAllocator>& v)
  {
    s << indent << "frameCount: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frameCount);
    s << indent << "boardWidth: ";
    Printer<int32_t>::stream(s, indent + "  ", v.boardWidth);
    s << indent << "boardHeight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.boardHeight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_CALIBRATION_NODE_MESSAGE_CALIBRATELENSREQUEST_H
